apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
        - name: front-server
          image: ghcr.io/belf-kr/front-server/nextjs-prod
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 5m
              memory: 100Mi
            limits:
              cpu: 5m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: front-server
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: front-server
