apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-server
  template:
    metadata:
      labels:
        app: front-server
    spec:
      containers:
        - name: front-server
          image: ghcr.io/belf-kr/front-server/nextjs:v0.1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-server
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: front-server
---
apiVersion: v1
kind: Service
metadata:
  name: external-front-server
  namespace: ingress-basic
spec:
  type: ExternalName
  externalName: front-server.test
