name: aks prod deploy

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_HOST: ghcr.io/${{ github.repository }}
  IMAGE_NAME: nextjs
  IMAGE_TAG: ${{ github.ref }}#refs/*/
  NAMESPACE: test

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: log test
        run: |
          echo github.ref="${{ github.ref }}"
          echo github.ref="${{ env.IMAGE_TAG }}"
