name: aks prod deploy

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_HOST: ghcr.io/${{ github.repository }}
  IMAGE_NAME: nextjs
  IMAGE_TAG: "주입 받음"
  NAMESPACE: test

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: get release version
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: log test
        run: |
          echo github.ref="${{ github.ref }}"
          echo github.ref="${{ env.IMAGE_TAG }}"
